# -*- coding: utf-8 -*-
"""Q5_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fLBYgrxvEcH2qfm0URlFaLuEUyLMibB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from preprocessing.polynomial_features import PolynomialFeatures
from linearRegression.linear_regression import LinearRegression
import os.path
from os import path

if not path.exists('Plots/Question5/'):
    os.makedirs('Plots/Question5/')

# TODO : Write here
x = np.array([i*np.pi/180 for i in range(60,300,2)])
y = 3*x + 8 + np.random.normal(0,3,len(x))
x = np.array([x]).T

tnorms = []
degs = [1, 3, 5, 7, 9]

for i in degs:
  poly = PolynomialFeatures(degree=i, include_bias=False)
  X = poly.transform(x)
  LR = LinearRegression(fit_intercept=True)
  LR.fit_normal_equations(X, y)
  yhat = LR.predict(X)
  tn = np.linalg.norm(LR.coef_)
  print('For degree =', i)
  print('Theta norm: ', tn)
  tnorms.append(tn)
  print("---------------------------")

plt.plot(degs, tnorms)
plt.show()